- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Set up nginx as proxy
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload nginx

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true
